name: Languages extract compile

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Extract FormatJS
        run: npm run extract -- 'src/**/*.ts*' --ignore='**/*.d.ts' --out-file languages/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'

      - name: Compile EN language
        run: npm run compile -- languages/en.json --ast --out-file src/languages/en.json

      - name: Compile CA language
        run: npm run compile -- languages/ca.json --ast --out-file src/languages/ca.json

      - name: Compile ES language
        run: npm run compile -- languages/es.json --ast --out-file src/languages/es.json
